spring.datasource.url=jdbc:mysql://localhost:3306/aibanking?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=PraneethReddy@39

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=supersecurejwtkeysupersecurejwtkey123456
jwt.expiration=86400000

server.port=8080
